@startuml
skinparam classAttributeIconSize 0

abstract class Creator {
    +factoryMethod()
}
abstract class Product

class ConcreteCreator
class ConcreteProduct

ConcreteCreator -up-|> Creator
ConcreteProduct -up-|> Product

ConcreteCreator .left.> ConcreteProduct : 依赖具体产品

@enduml