CREATE DATABASE IF NOT EXISTS demos;
USE demos;
DROP TABLE IF EXISTS `USER`;
CREATE TABLE `USER` (
  `ID` int(22) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `USERNAME` varchar(50) NOT NULL DEFAULT '' COMMENT '用户名',
  PRIMARY KEY (`ID`)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='测试表';

INSERT INTO `USER` VALUES ('1', 'admin');
INSERT INTO `USER` VALUES ('2', 'gorden5566');
INSERT INTO `USER` VALUES ('3', 'test');