@startuml
skinparam classAttributeIconSize 0

class Client
class Invoker
abstract class Command {
    +execute()
}
class Receiver {
    +action()
}
class ConcreteCommand

Invoker o-right-> Command
ConcreteCommand -up-|> Command
ConcreteCommand -left-> Receiver : +receiver

Client -down-> Receiver
Client .down.> ConcreteCommand


@enduml