@startuml
skinparam classAttributeIconSize 0

class Client
abstract class Handler {
    +handlerRequest()
}
class ConcreteHandler

ConcreteHandler -up-|> Handler
Handler --> Handler : +successor
Client -right-> Handler

@enduml