@startuml
skinparam classAttributeIconSize 0

class Director {
    +construct()
}
abstract class Builder {
    +buildPart()
}
class ConcreteBuilder
class Product

ConcreteBuilder -up-|> Builder
ConcreteBuilder .right.> Product : 依赖
Director o-right-> Builder : +builder

@enduml