@startuml
skinparam classAttributeIconSize 0

class Director
abstract class Builder
class ConcreteProduct
class Product

ConcreteProduct -up-|> Builder
ConcreteProduct .right.> Product : 依赖
Director o-right-> Builder : +builder

@enduml