@startuml
skinparam classAttributeIconSize 0

class Director
abstract class Builder
class ConcreteBuilder
class Product

ConcreteBuilder -up-|> Builder
ConcreteBuilder .right.> Product : 依赖
Director o-right-> Builder : +builder

@enduml