@startuml
skinparam classAttributeIconSize 0

abstract class State {
    +handle()
}
class ConcreteState
class Context {
    +request()
}

ConcreteState -up-|> State
Context o-right-> State : +state



@enduml